// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: '1:581515594229:web:866a646c6a6b2d584078bc',
    messagingSenderId: '581515594229',
    projectId: 'project-1-2a682',
    authDomain: 'project-1-2a682.firebaseapp.com',
    storageBucket: 'project-1-2a682.appspot.com',
    measurementId: 'G-T69B014256',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API KEY',
    appId: '1:581515594229:android:27ede1ed45c1f7314078bc',
    messagingSenderId: '581515594229',
    projectId: 'project-1-2a682',
    storageBucket: 'project-1-2a682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API KEY',
    appId: '1:581515594229:ios:72cc068a447321cd4078bc',
    messagingSenderId: '581515594229',
    projectId: 'project-1-2a682',
    storageBucket: 'project-1-2a682.appspot.com',
    iosBundleId: 'com.example.connor917610885A1F24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'API KEY',
    appId: '1:581515594229:ios:72cc068a447321cd4078bc',
    messagingSenderId: '581515594229',
    projectId: 'project-1-2a682',
    storageBucket: 'project-1-2a682.appspot.com',
    iosBundleId: 'com.example.connor917610885A1F24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'API KEY',
    appId: '1:581515594229:web:fe5f43646650a4154078bc',
    messagingSenderId: '581515594229',
    projectId: 'project-1-2a682',
    authDomain: 'project-1-2a682.firebaseapp.com',
    storageBucket: 'project-1-2a682.appspot.com',
    measurementId: 'G-RSQG2CC07R',
  );
}
